name: chat_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: ArialNova
      fonts:
        - asset: assets/fonts/arial/ArialNova.ttf
        - asset: assets/fonts/arial/ArialNova-Bold.ttf
          weight: 700
        - asset: assets/fonts/arial/ArialNova-Light.ttf
          weight: 300
        - asset: assets/fonts/arial/ArialNovaCond.ttf
        - asset: assets/fonts/arial/ArialNovaCond-Bold.ttf
          weight: 700
        - asset: assets/fonts/arial/ArialNovaCond-Light.ttf
          weight: 300
        - asset: assets/fonts/arial/ArialNova-Italic.ttf
          style: italic
        - asset: assets/fonts/arial/ArialNovaCond-Italic.ttf
          style: italic
        - asset: assets/fonts/arial/ArialNova-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/arial/ArialNova-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/arial/ArialNovaCond-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/arial/ArialNovaCond-LightItalic.ttf
          weight: 300
          style: italic
